name: ticketing_apps
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  flutter_svg_provider: ^1.0.7
  google_fonts: ^8.0.0
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  timer_count_down: ^2.2.2
  flutter_spinkit: ^5.2.2
  flutter_bloc: ^9.1.1
  freezed: ^3.2.5
  freezed_annotation: ^3.1.0
  http: ^1.6.0
  dartz: ^0.10.1
  shared_preferences: ^2.5.4
  connectivity_plus: ^7.0.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.12.0
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5


flutter:
  uses-material-design: true

  assets:
    - assets/icons/nav/
    - assets/icons/payment/
    - assets/icons/settings/
    - assets/images/
    - assets/icons/
  
flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
 
  
  
  
